[package]
name = "lemur"
authors = ["Robert Jacobson <rljacobson@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "A pattern matching engine that supports commutative and associative theories."
categories = ["algorithms", "compilers", "parsing", "mathematics"]
keywords = ["computer algebra", "Mathematica", "pattern matching", "term rewriting"]
website = "http://www.github.com/rljacobson/loris"
repository = "http://www.github.com/rljacobson/loris"
license = "BSD"


publish = false


[dependencies]
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
fnv = { version = "1"}
strange = {path = "../strange"}
permutations = "0.1.1"
lazy_static = "1.4.0"
tinyvec = "1.5.1"
